### ISSUE TITLE
Travis integration

### ISSUE THREAD

**Issue by tdenewiler** [RoboPubs/Publications#2]
We should set this repository up so that any new commits to the master branch (straight to master, or via pull requests) trigger a Travis CI job that will build and deploy this site to GitHub Pages. That site is located at https://robopubs.github.io/Publications/.

More information on how to configure Travis and this repository is at https://docs.travis-ci.com/user/deployment/pages/.

Further guides are at:
https://derekweitzel.com/2017/02/08/deploying-docs-on-github-with-travisci/
https://stackoverflow.com/questions/50892018/auto-build-an-mkdocs-documentation-in-travis-ci

**Comment by RoboPubs** [comment]
This is working with #6. Also had to change the settings for this repository to generate Pages using the source branch of `gh-pages` instead of `master`.
