### ISSUE TITLE
Split pages by decade

### ISSUE THREAD

**Issue by tdenewiler** [RoboPubs/Publications#5]
The current setup is to have each year listed on the main page, with only the current year open by default. This allows content to fit well on screens. The downside is that it makes searching in the page more difficult.

The current method of having an expand/collapse all button is a nice approach to making search work better.

I also like the approach of having a separate page for each decade, with all of the years open by default on the respective decade pages. This will allow for more separation in the number of files -- we would move from one very large file to multiple smaller files. Even if this approach is taken, I think adding an expand/collapse button on each decade page would be nice.

**Comment by RoboPubs** [comment]
This experiment did not work as well as planned.
